CREATE TABLE evento_alpr
(
    id_alpr    NUMBER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    moto_id    NUMBER,
    placa_lida VARCHAR(255)                            NOT NULL,
    url_imagem VARCHAR(255),
    ts_alpr    TIMESTAMP,
    CONSTRAINT pk_eventoalpr PRIMARY KEY (id_alpr)
);

CREATE TABLE evento_wifi
(
    id_evento_wifi     NUMBER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    moto_id            NUMBER,
    gateway_id_gateway NUMBER,
    rssits_evento      INTEGER,
    CONSTRAINT pk_eventowifi PRIMARY KEY (id_evento_wifi)
);

CREATE TABLE gateway
(
    id_gateway      NUMBER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    mac_address     VARCHAR(255)                            NOT NULL,
    descricao       VARCHAR(255),
    localid_zona_id NUMBER,
    CONSTRAINT pk_gateway PRIMARY KEY (id_gateway)
);

CREATE TABLE moto
(
    id      NUMBER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    modelo  VARCHAR(255),
    placa   VARCHAR(7),
    zona_id NUMBER ,
    status  SMALLINT,
    CONSTRAINT pk_moto PRIMARY KEY (id)
);

CREATE TABLE patio
(
    id               NUMBER  GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    nome             VARCHAR(255),
    quantidade_vagas INTEGER,
    metragem_zonaa   DOUBLE PRECISION,
    metragem_zonab   DOUBLE PRECISION,
    CONSTRAINT pk_patio PRIMARY KEY (id)
);

CREATE TABLE zona
(
    id       NUMBER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    tipo     VARCHAR(255),
    metragem DOUBLE PRECISION,
    nome     VARCHAR(255)                            NOT NULL,
    patio_id NUMBER                                   NOT NULL,
    CONSTRAINT pk_zona PRIMARY KEY (id)
);

ALTER TABLE gateway
    ADD CONSTRAINT uc_gateway_mac_address UNIQUE (mac_address);

ALTER TABLE moto
    ADD CONSTRAINT uc_moto_placa UNIQUE (placa);

ALTER TABLE patio
    ADD CONSTRAINT uc_patio_nome UNIQUE (nome);

ALTER TABLE zona
    ADD CONSTRAINT uc_zona_nome UNIQUE (nome);

ALTER TABLE evento_alpr
    ADD CONSTRAINT FK_EVENTOALPR_ON_MOTO FOREIGN KEY (moto_id) REFERENCES moto (id);

ALTER TABLE evento_wifi
    ADD CONSTRAINT FK_EVENTOWIFI_ON_GATEWAY_ID_GATEWAY FOREIGN KEY (gateway_id_gateway) REFERENCES gateway (id_gateway);

ALTER TABLE evento_wifi
    ADD CONSTRAINT FK_EVENTOWIFI_ON_MOTO FOREIGN KEY (moto_id) REFERENCES moto (id);

ALTER TABLE gateway
    ADD CONSTRAINT FK_GATEWAY_ON_LOCALID_ZONA FOREIGN KEY (localid_zona_id) REFERENCES zona (id);

ALTER TABLE moto
    ADD CONSTRAINT FK_MOTO_ON_ZONA FOREIGN KEY (zona_id) REFERENCES zona (id);

ALTER TABLE zona
    ADD CONSTRAINT FK_ZONA_ON_PATIO FOREIGN KEY (patio_id) REFERENCES patio (id);