ALTER TABLE moto
    ADD patio_id BIGINT;

ALTER TABLE moto
    ALTER COLUMN patio_id SET NOT NULL;

ALTER TABLE zona
    ADD tipo_zona VARCHAR(255);

ALTER TABLE moto
    ADD CONSTRAINT FK_MOTO_PATIO FOREIGN KEY (patio_id) REFERENCES patio (id);

ALTER TABLE zona
DROP
COLUMN tipo;

ALTER TABLE moto
ALTER
COLUMN placa TYPE VARCHAR(255) USING (placa::VARCHAR(255));