CREATE TABLE usuario (
                         id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                         email VARCHAR2(255) UNIQUE,
                         name VARCHAR2(255),
                         password VARCHAR2(255),
                         avatar_url VARCHAR2(255),
                         score NUMBER NOT NULL
);

ALTER TABLE zona ADD CONSTRAINT uq_zona_patio_tipo UNIQUE (patio_id, tipo_zona);

ALTER TABLE patio MODIFY (quantidade_vagas NOT NULL);
ALTER TABLE zona MODIFY (tipo_zona NOT NULL);

ALTER TABLE zona ADD CONSTRAINT ck_zona_tipo_zona CHECK (tipo_zona IN ('A','B'));

CREATE INDEX idx_zona_patio ON zona(patio_id);
