CREATE TABLE usuario (
                         id_user NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                         email VARCHAR2(255) UNIQUE,
                         nome_user VARCHAR2(255),
                         password VARCHAR2(255),
                         phone VARCHAR2(20)
);
ALTER TABLE zona ADD CONSTRAINT uq_zona_patio_tipo UNIQUE (patio_id, tipo_zona);

ALTER TABLE patio MODIFY (quantidade_vagas NOT NULL);
ALTER TABLE zona MODIFY (tipo_zona NOT NULL);

ALTER TABLE zona ADD CONSTRAINT ck_zona_tipo_zona CHECK (tipo_zona IN ('A','B'));

CREATE INDEX idx_zona_patio ON zona(patio_id);

ALTER TABLE patio MODIFY (metragem_zonaa NOT NULL);
ALTER TABLE patio MODIFY (metragem_zonab NOT NULL);
ALTER TABLE moto MODIFY (placa VARCHAR2(7));
